name: release

on:
  release:
    types: [published, edited, released]

jobs:
  rollout-staging:
    if: github.event.release.prerelease

    runs-on: ubuntu-latest

    steps:
      - name: Test Output
        run: echo "Prerelease $VERSION"
        env:
          VERSION: ${{ github.event.release.tag_name }}

  rollout-production:
    if: "!github.event.release.prerelease"

    runs-on: ubuntu-latest

    steps:
      - name: Test Output
        run: echo "Yay! Release $VERSION"
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.CHANNEL_NAME }}
          SLACK_ICON: https://avatars3.githubusercontent.com/u/32634858?size=48
          SLACK_MESSAGE: ${{ github.event.release.tag_name }}
          SLACK_TITLE: 'Hello from Github Actions :rocket:'
          SLACK_USERNAME: Geoffrey
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
