name: release

on:
  release:
    types: [published, edited, released]

jobs:
  rollout-staging:
    if: github.event.release.prerelease

    runs-on: ubuntu-latest

    steps:
      - name: Test Output
        run: echo "Prerelease $VERSION"
        env:
          VERSION: ${{ github.event.release.tag_name }}

